version: v2
name: Pylint
slug: pylint
type: content
summary: Code analysis for Python
description: Code analysis for Python
beta: true
default_configuration:
  installation:
    repo_languages:
      - Python
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
