name: Pylint
slug: pylint
type: content
description: |
  Fill me out
parameters:
  - name: foo
    description: bar
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
